export const ALL_LISTING_REQUEST = "ALL_LISTING_REQUEST";
export const ALL_LISTING_SUCCESS = "ALL_LISTING_SUCCESS";
export const ALL_LISTING_FAIL = "ALL_LISTING_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";